
package com.amadeus.xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.amadeus.wsdl._2010._06.ws.link_v1.TransactionFlowLinkType;
import com.amadeus.xml._2010._06.security_v1.AMASecurityHostedUser;
import com.amadeus.xml._2010._06.session_v3.Session;
import com.amadeus.xml.cltreq_04_1_ia.PNRIgnore;
import com.amadeus.xml.cltres_04_1_ia.PNRIgnoreReply;
import com.amadeus.xml.ffareq_04_1_1a.PNRAddFrequentFlyer;
import com.amadeus.xml.ffares_04_1_1a.PNRAddFrequentFlyerReply;
import com.amadeus.xml.fmpcaq_14_3_1a.FareMasterPricerCalendar;
import com.amadeus.xml.fmpcar_14_3_1a.FareMasterPricerCalendarReply;
import com.amadeus.xml.fmptbq_14_3_1a.FareMasterPricerTravelBoardSearch;
import com.amadeus.xml.fmptbr_14_3_1a.FareMasterPricerTravelBoardSearchReply;
import com.amadeus.xml.hsfreq_07_3_1a.CommandCryptic;
import com.amadeus.xml.hsfres_07_3_1a.CommandCrypticReply;
import com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation;
import com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply;
import com.amadeus.xml.pnracc_15_1_1a.PNRReply;
import com.amadeus.xml.pnradd_15_1_1a.PNRAddMultiElements;
import com.amadeus.xml.pnrret_15_1_1a.PNRRetrieve;
import com.amadeus.xml.pnrxcl_15_1_1a.PNRCancel;
import com.amadeus.xml.pretrq_14_1_1a.PNRRetrieveByRecLoc;
import com.amadeus.xml.qcsdrq_13_1_1a.QueueCountTotal;
import com.amadeus.xml.qcsdrr_13_1_1a.QueueCountTotalReply;
import com.amadeus.xml.qdqlrq_11_1_1a.QueueList;
import com.amadeus.xml.qdqlrr_11_1_1a.QueueListReply;
import com.amadeus.xml.quereq_09_1_ia.QueueModeProcessQueue;
import com.amadeus.xml.queres_09_1_ia.QueueModeProcessQueueReply;
import com.amadeus.xml.quqmdq_03_1_1a.QueueRemoveItem;
import com.amadeus.xml.quqmdr_03_1_1a.QueueRemoveItemReply;
import com.amadeus.xml.quqmuq_03_1_1a.QueueMoveItem;
import com.amadeus.xml.quqmur_03_1_1a.QueueMoveItemReply;
import com.amadeus.xml.quqpcq_03_1_1a.QueuePlacePNR;
import com.amadeus.xml.quqpcr_03_1_1a.QueuePlacePNRReply;
import com.amadeus.xml.smpreq_14_2_1a.AirRetrieveSeatMap;
import com.amadeus.xml.smpres_14_2_1a.AirRetrieveSeatMapReply;
import com.amadeus.xml.tatreq_15_2_1a.TicketProcessEDoc;
import com.amadeus.xml.tatres_15_2_1a.TicketProcessEDocReply;
import com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing;
import com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply;
import com.amadeus.xml.tfopcq_15_4_1a.FOPCreateFormOfPayment;
import com.amadeus.xml.tfopcr_15_4_1a.FOPCreateFormOfPaymentReply;
import com.amadeus.xml.tibnrq_15_1_1a.FareInformativeBestPricingWithoutPNR;
import com.amadeus.xml.tibnrr_15_1_1a.FareInformativeBestPricingWithoutPNRReply;
import com.amadeus.xml.tktreq_04_1_ia.TicketProcessETicket;
import com.amadeus.xml.tktres_04_1_ia.TicketProcessETicketReply;
import com.amadeus.xml.tmdsiq_15_1_1a.DocIssuanceIssueMiscellaneousDocuments;
import com.amadeus.xml.tmdsir_15_1_1a.DocIssuanceIssueMiscellaneousDocumentsReply;
import com.amadeus.xml.tnlres_00_1_1a.PNRList;
import com.amadeus.xml.tpcbrq_15_1_1a.FarePricePNRWithBookingClass;
import com.amadeus.xml.tpcbrr_15_1_1a.FarePricePNRWithBookingClassReply;
import com.amadeus.xml.tplfrq_15_1_1a.FarePricePNRWithLowerFares;
import com.amadeus.xml.tplfrr_15_1_1a.FarePricePNRWithLowerFaresReply;
import com.amadeus.xml.tplprq_14_1_1a.FarePricePNRWithLowestFare;
import com.amadeus.xml.tplprr_14_1_1a.FarePricePNRWithLowestFareReply;
import com.amadeus.xml.ttktiq_15_1_1a.DocIssuanceIssueTicket;
import com.amadeus.xml.ttktir_15_1_1a.DocIssuanceIssueTicketReply;
import com.amadeus.xml.vlsslq_06_1_1a.SecurityAuthenticate;
import com.amadeus.xml.vlsslr_06_1_1a.SecurityAuthenticateReply;
import com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut;
import com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmadeusWebServicesPT", targetNamespace = "http://xml.amadeus.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.amadeus.xml._2010._06.security_v1.ObjectFactory.class,
    com.amadeus.xml.cltreq_04_1_ia.ObjectFactory.class,
    com.amadeus.xml.cltres_04_1_ia.ObjectFactory.class,
    com.amadeus.xml.ffareq_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.ffares_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.fmpcaq_14_3_1a.ObjectFactory.class,
    com.amadeus.xml.fmpcar_14_3_1a.ObjectFactory.class,
    com.amadeus.xml.fmptbq_14_3_1a.ObjectFactory.class,
    com.amadeus.xml.fmptbr_14_3_1a.ObjectFactory.class,
    com.amadeus.xml.hsfreq_07_3_1a.ObjectFactory.class,
    com.amadeus.xml.hsfres_07_3_1a.ObjectFactory.class,
    com.amadeus.xml.itareq_05_2_ia.ObjectFactory.class,
    com.amadeus.xml.itares_05_2_ia.ObjectFactory.class,
    com.amadeus.xml.pnracc_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnradd_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnrret_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnrxcl_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.pretrq_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.qcsdrq_13_1_1a.ObjectFactory.class,
    com.amadeus.xml.qcsdrr_13_1_1a.ObjectFactory.class,
    com.amadeus.xml.qdqlrq_11_1_1a.ObjectFactory.class,
    com.amadeus.xml.qdqlrr_11_1_1a.ObjectFactory.class,
    com.amadeus.xml.quereq_09_1_ia.ObjectFactory.class,
    com.amadeus.xml.queres_09_1_ia.ObjectFactory.class,
    com.amadeus.xml.quqmdq_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.quqmdr_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.quqmuq_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.quqmur_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.quqpcq_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.quqpcr_03_1_1a.ObjectFactory.class,
    com.amadeus.xml.smpreq_14_2_1a.ObjectFactory.class,
    com.amadeus.xml.smpres_14_2_1a.ObjectFactory.class,
    com.amadeus.xml.tatreq_15_2_1a.ObjectFactory.class,
    com.amadeus.xml.tatres_15_2_1a.ObjectFactory.class,
    com.amadeus.xml.tautcq_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.tautcr_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.tfopcq_15_4_1a.ObjectFactory.class,
    com.amadeus.xml.tfopcr_15_4_1a.ObjectFactory.class,
    com.amadeus.xml.tibnrq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tibnrr_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tktreq_04_1_ia.ObjectFactory.class,
    com.amadeus.xml.tktres_04_1_ia.ObjectFactory.class,
    com.amadeus.xml.tmdsiq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tmdsir_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tnlres_00_1_1a.ObjectFactory.class,
    com.amadeus.xml.tpcbrq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tpcbrr_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tplfrq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tplfrr_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.tplprq_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.tplprr_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.ttktiq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.ttktir_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlsslq_06_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlsslr_06_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssoq_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssor_04_1_1a.ObjectFactory.class,
    org.iata.iata._2007._00.iata2010.ObjectFactory.class,
    org.opentravel.ota._2003._05.ota2010b.ObjectFactory.class,
    com.amadeus.xml._2010._06.types_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.appmdw_commontypes_v3.ObjectFactory.class,
    com.amadeus.wsdl._2010._06.ws.link_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.session_v3.ObjectFactory.class
})
public interface AmadeusWebServicesPT {


    /**
     * 
     * @param airRetrieveSeatMap142
     * @param security
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.smpres_14_2_1a.AirRetrieveSeatMapReply
     */
    @WebMethod(operationName = "Air_RetrieveSeatMap", action = "http://webservices.amadeus.com/SMPREQ_14_2_1A")
    @WebResult(name = "Air_RetrieveSeatMapReply", targetNamespace = "http://xml.amadeus.com/SMPRES_14_2_1A", partName = "Air_RetrieveSeatMapReply_14_2")
    public AirRetrieveSeatMapReply airRetrieveSeatMap(
        @WebParam(name = "Air_RetrieveSeatMap", targetNamespace = "http://xml.amadeus.com/SMPREQ_14_2_1A", partName = "Air_RetrieveSeatMap_14_2")
        AirRetrieveSeatMap airRetrieveSeatMap142,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param airSellFromRecommendation52
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply
     */
    @WebMethod(operationName = "Air_SellFromRecommendation", action = "http://webservices.amadeus.com/ITAREQ_05_2_IA")
    @WebResult(name = "Air_SellFromRecommendationReply", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", partName = "Air_SellFromRecommendationReply_5_2")
    public AirSellFromRecommendationReply airSellFromRecommendation(
        @WebParam(name = "Air_SellFromRecommendation", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA", partName = "Air_SellFromRecommendation_5_2")
        AirSellFromRecommendation airSellFromRecommendation52,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param commandCryptic73
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.hsfres_07_3_1a.CommandCrypticReply
     */
    @WebMethod(operationName = "Command_Cryptic", action = "http://webservices.amadeus.com/HSFREQ_07_3_1A")
    @WebResult(name = "Command_CrypticReply", targetNamespace = "http://xml.amadeus.com/HSFRES_07_3_1A", partName = "Command_CrypticReply_7_3")
    public CommandCrypticReply commandCryptic(
        @WebParam(name = "Command_Cryptic", targetNamespace = "http://xml.amadeus.com/HSFREQ_07_3_1A", partName = "Command_Cryptic_7_3")
        CommandCryptic commandCryptic73,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param docIssuanceIssueMiscellaneousDocuments151
     * @return
     *     returns com.amadeus.xml.tmdsir_15_1_1a.DocIssuanceIssueMiscellaneousDocumentsReply
     */
    @WebMethod(operationName = "DocIssuance_IssueMiscellaneousDocuments", action = "http://webservices.amadeus.com/TMDSIQ_15_1_1A")
    @WebResult(name = "DocIssuance_IssueMiscellaneousDocumentsReply", targetNamespace = "http://xml.amadeus.com/TMDSIR_15_1_1A", partName = "DocIssuance_IssueMiscellaneousDocumentsReply_15_1")
    public DocIssuanceIssueMiscellaneousDocumentsReply docIssuanceIssueMiscellaneousDocuments(
        @WebParam(name = "DocIssuance_IssueMiscellaneousDocuments", targetNamespace = "http://xml.amadeus.com/TMDSIQ_15_1_1A", partName = "DocIssuance_IssueMiscellaneousDocuments_15_1")
        DocIssuanceIssueMiscellaneousDocuments docIssuanceIssueMiscellaneousDocuments151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param docIssuanceIssueTicket151
     * @param link
     * @return
     *     returns com.amadeus.xml.ttktir_15_1_1a.DocIssuanceIssueTicketReply
     */
    @WebMethod(operationName = "DocIssuance_IssueTicket", action = "http://webservices.amadeus.com/TTKTIQ_15_1_1A")
    @WebResult(name = "DocIssuance_IssueTicketReply", targetNamespace = "http://xml.amadeus.com/TTKTIR_15_1_1A", partName = "DocIssuance_IssueTicketReply_15_1")
    public DocIssuanceIssueTicketReply docIssuanceIssueTicket(
        @WebParam(name = "DocIssuance_IssueTicket", targetNamespace = "http://xml.amadeus.com/TTKTIQ_15_1_1A", partName = "DocIssuance_IssueTicket_15_1")
        DocIssuanceIssueTicket docIssuanceIssueTicket151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param fopCreateFormOfPayment154
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.tfopcr_15_4_1a.FOPCreateFormOfPaymentReply
     */
    @WebMethod(operationName = "FOP_CreateFormOfPayment", action = "http://webservices.amadeus.com/TFOPCQ_15_4_1A")
    @WebResult(name = "FOP_CreateFormOfPaymentReply", targetNamespace = "http://xml.amadeus.com/TFOPCR_15_4_1A", partName = "FOP_CreateFormOfPaymentReply_15_4")
    public FOPCreateFormOfPaymentReply fopCreateFormOfPayment(
        @WebParam(name = "FOP_CreateFormOfPayment", targetNamespace = "http://xml.amadeus.com/TFOPCQ_15_4_1A", partName = "FOP_CreateFormOfPayment_15_4")
        FOPCreateFormOfPayment fopCreateFormOfPayment154,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param fareInformativeBestPricingWithoutPNR151
     * @param security
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.tibnrr_15_1_1a.FareInformativeBestPricingWithoutPNRReply
     */
    @WebMethod(operationName = "Fare_InformativeBestPricingWithoutPNR", action = "http://webservices.amadeus.com/TIBNRQ_15_1_1A")
    @WebResult(name = "Fare_InformativeBestPricingWithoutPNRReply", targetNamespace = "http://xml.amadeus.com/TIBNRR_15_1_1A", partName = "Fare_InformativeBestPricingWithoutPNRReply_15_1")
    public FareInformativeBestPricingWithoutPNRReply fareInformativeBestPricingWithoutPNR(
        @WebParam(name = "Fare_InformativeBestPricingWithoutPNR", targetNamespace = "http://xml.amadeus.com/TIBNRQ_15_1_1A", partName = "Fare_InformativeBestPricingWithoutPNR_15_1")
        FareInformativeBestPricingWithoutPNR fareInformativeBestPricingWithoutPNR151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param fareMasterPricerCalendar143
     * @return
     *     returns com.amadeus.xml.fmpcar_14_3_1a.FareMasterPricerCalendarReply
     */
    @WebMethod(operationName = "Fare_MasterPricerCalendar", action = "http://webservices.amadeus.com/FMPCAQ_14_3_1A")
    @WebResult(name = "Fare_MasterPricerCalendarReply", targetNamespace = "http://xml.amadeus.com/FMPCAR_14_3_1A", partName = "Fare_MasterPricerCalendarReply_14_3")
    public FareMasterPricerCalendarReply fareMasterPricerCalendar(
        @WebParam(name = "Fare_MasterPricerCalendar", targetNamespace = "http://xml.amadeus.com/FMPCAQ_14_3_1A", partName = "Fare_MasterPricerCalendar_14_3")
        FareMasterPricerCalendar fareMasterPricerCalendar143,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param fareMasterPricerTravelBoardSearch143
     * @param link
     * @return
     *     returns com.amadeus.xml.fmptbr_14_3_1a.FareMasterPricerTravelBoardSearchReply
     */
    @WebMethod(operationName = "Fare_MasterPricerTravelBoardSearch", action = "http://webservices.amadeus.com/FMPTBQ_14_3_1A")
    @WebResult(name = "Fare_MasterPricerTravelBoardSearchReply", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_3_1A", partName = "Fare_MasterPricerTravelBoardSearchReply_14_3")
    public FareMasterPricerTravelBoardSearchReply fareMasterPricerTravelBoardSearch(
        @WebParam(name = "Fare_MasterPricerTravelBoardSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_3_1A", partName = "Fare_MasterPricerTravelBoardSearch_14_3")
        FareMasterPricerTravelBoardSearch fareMasterPricerTravelBoardSearch143,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param farePricePNRWithBookingClass151
     * @return
     *     returns com.amadeus.xml.tpcbrr_15_1_1a.FarePricePNRWithBookingClassReply
     */
    @WebMethod(operationName = "Fare_PricePNRWithBookingClass", action = "http://webservices.amadeus.com/TPCBRQ_15_1_1A")
    @WebResult(name = "Fare_PricePNRWithBookingClassReply", targetNamespace = "http://xml.amadeus.com/TPCBRR_15_1_1A", partName = "Fare_PricePNRWithBookingClassReply_15_1")
    public FarePricePNRWithBookingClassReply farePricePNRWithBookingClass(
        @WebParam(name = "Fare_PricePNRWithBookingClass", targetNamespace = "http://xml.amadeus.com/TPCBRQ_15_1_1A", partName = "Fare_PricePNRWithBookingClass_15_1")
        FarePricePNRWithBookingClass farePricePNRWithBookingClass151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param farePricePNRWithLowerFares151
     * @return
     *     returns com.amadeus.xml.tplfrr_15_1_1a.FarePricePNRWithLowerFaresReply
     */
    @WebMethod(operationName = "Fare_PricePNRWithLowerFares", action = "http://webservices.amadeus.com/TPLFRQ_15_1_1A")
    @WebResult(name = "Fare_PricePNRWithLowerFaresReply", targetNamespace = "http://xml.amadeus.com/TPLFRR_15_1_1A", partName = "Fare_PricePNRWithLowerFaresReply_15_1")
    public FarePricePNRWithLowerFaresReply farePricePNRWithLowerFares(
        @WebParam(name = "Fare_PricePNRWithLowerFares", targetNamespace = "http://xml.amadeus.com/TPLFRQ_15_1_1A", partName = "Fare_PricePNRWithLowerFares_15_1")
        FarePricePNRWithLowerFares farePricePNRWithLowerFares151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param farePricePNRWithLowestFare141
     * @param link
     * @return
     *     returns com.amadeus.xml.tplprr_14_1_1a.FarePricePNRWithLowestFareReply
     */
    @WebMethod(operationName = "Fare_PricePNRWithLowestFare", action = "http://webservices.amadeus.com/TPLPRQ_14_1_1A")
    @WebResult(name = "Fare_PricePNRWithLowestFareReply", targetNamespace = "http://xml.amadeus.com/TPLPRR_14_1_1A", partName = "Fare_PricePNRWithLowestFareReply_14_1")
    public FarePricePNRWithLowestFareReply farePricePNRWithLowestFare(
        @WebParam(name = "Fare_PricePNRWithLowestFare", targetNamespace = "http://xml.amadeus.com/TPLPRQ_14_1_1A", partName = "Fare_PricePNRWithLowestFare_14_1")
        FarePricePNRWithLowestFare farePricePNRWithLowestFare141,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param pnrAddFrequentFlyer41
     * @param link
     * @return
     *     returns com.amadeus.xml.ffares_04_1_1a.PNRAddFrequentFlyerReply
     */
    @WebMethod(operationName = "PNR_AddFrequentFlyer", action = "http://webservices.amadeus.com/FFAREQ_04_1_1A")
    @WebResult(name = "PNR_AddFrequentFlyerReply", targetNamespace = "http://xml.amadeus.com/FFARES_04_1_1A", partName = "PNR_AddFrequentFlyerReply_4_1")
    public PNRAddFrequentFlyerReply pnrAddFrequentFlyer(
        @WebParam(name = "PNR_AddFrequentFlyer", targetNamespace = "http://xml.amadeus.com/FFAREQ_04_1_1A", partName = "PNR_AddFrequentFlyer_4_1")
        PNRAddFrequentFlyer pnrAddFrequentFlyer41,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param pnrAddMultiElements151
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.pnracc_15_1_1a.PNRReply
     */
    @WebMethod(operationName = "PNR_AddMultiElements", action = "http://webservices.amadeus.com/PNRADD_15_1_1A")
    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_15_1_1A", partName = "PNR_Reply_15_1")
    public PNRReply pnrAddMultiElements(
        @WebParam(name = "PNR_AddMultiElements", targetNamespace = "http://xml.amadeus.com/PNRADD_15_1_1A", partName = "PNR_AddMultiElements_15_1")
        PNRAddMultiElements pnrAddMultiElements151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param pnrCancel151
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.pnracc_15_1_1a.PNRReply
     */
    @WebMethod(operationName = "PNR_Cancel", action = "http://webservices.amadeus.com/PNRXCL_15_1_1A")
    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_15_1_1A", partName = "PNR_Reply_15_1")
    public PNRReply pnrCancel(
        @WebParam(name = "PNR_Cancel", targetNamespace = "http://xml.amadeus.com/PNRXCL_15_1_1A", partName = "PNR_Cancel_15_1")
        PNRCancel pnrCancel151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param pnrIgnore41
     * @param link
     * @return
     *     returns com.amadeus.xml.cltres_04_1_ia.PNRIgnoreReply
     */
    @WebMethod(operationName = "PNR_Ignore", action = "http://webservices.amadeus.com/CLTREQ_04_1_IA")
    @WebResult(name = "PNR_IgnoreReply", targetNamespace = "http://xml.amadeus.com/CLTRES_04_1_IA", partName = "PNR_IgnoreReply_4_1")
    public PNRIgnoreReply pnrIgnore(
        @WebParam(name = "PNR_Ignore", targetNamespace = "http://xml.amadeus.com/CLTREQ_04_1_IA", partName = "PNR_Ignore_4_1")
        PNRIgnore pnrIgnore41,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param pnrRetrieve151
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.pnracc_15_1_1a.PNRReply
     */
    @WebMethod(operationName = "PNR_Retrieve", action = "http://webservices.amadeus.com/PNRRET_15_1_1A")
    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_15_1_1A", partName = "PNR_Reply_15_1")
    public PNRReply pnrRetrieve(
        @WebParam(name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_15_1_1A", partName = "PNR_Retrieve_15_1")
        PNRRetrieve pnrRetrieve151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param pnrRetrieve151
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.tnlres_00_1_1a.PNRList
     */
    @WebMethod(operationName = "PNR_Retrieve2", action = "http://webservices.amadeus.com/PNRRET_15_1_1A")
    @WebResult(name = "PNR_List", targetNamespace = "http://xml.amadeus.com/TNLRES_00_1_1A", partName = "PNR_List_0_1")
    public PNRList pnrRetrieve2(
        @WebParam(name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_15_1_1A", partName = "PNR_Retrieve_15_1")
        PNRRetrieve pnrRetrieve151,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param pnrRetrieveByRecLoc141
     * @param security
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.pretrr_14_1_1a.PNRRetrieveByRecLocReply
     */
    /*@WebMethod(operationName = "PNR_RetrieveByRecLoc", action = "http://webservices.amadeus.com/PRETRQ_14_1_1A")
    @WebResult(name = "PNR_RetrieveByRecLocReply", targetNamespace = "http://xml.amadeus.com/PRETRR_14_1_1A", partName = "PNR_RetrieveByRecLocReply_14_1")
    public PNRRetrieveByRecLocReply pnrRetrieveByRecLoc(
        @WebParam(name = "PNR_RetrieveByRecLoc", targetNamespace = "http://xml.amadeus.com/PRETRQ_14_1_1A", partName = "PNR_RetrieveByRecLoc_14_1")
        PNRRetrieveByRecLoc pnrRetrieveByRecLoc141,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);
*/
    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param queueModeProcessQueue91
     * @return
     *     returns com.amadeus.xml.queres_09_1_ia.QueueModeProcessQueueReply
     */
    @WebMethod(operationName = "QueueMode_ProcessQueue", action = "http://webservices.amadeus.com/QUEREQ_09_1_IA")
    @WebResult(name = "QueueMode_ProcessQueueReply", targetNamespace = "http://xml.amadeus.com/QUERES_09_1_IA", partName = "QueueMode_ProcessQueueReply_9_1")
    public QueueModeProcessQueueReply queueModeProcessQueue(
        @WebParam(name = "QueueMode_ProcessQueue", targetNamespace = "http://xml.amadeus.com/QUEREQ_09_1_IA", partName = "QueueMode_ProcessQueue_9_1")
        QueueModeProcessQueue queueModeProcessQueue91,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param queueCountTotal131
     * @return
     *     returns com.amadeus.xml.qcsdrr_13_1_1a.QueueCountTotalReply
     */
    @WebMethod(operationName = "Queue_CountTotal", action = "http://webservices.amadeus.com/QCSDRQ_13_1_1A")
    @WebResult(name = "Queue_CountTotalReply", targetNamespace = "http://xml.amadeus.com/QCSDRR_13_1_1A", partName = "Queue_CountTotalReply_13_1")
    public QueueCountTotalReply queueCountTotal(
        @WebParam(name = "Queue_CountTotal", targetNamespace = "http://xml.amadeus.com/QCSDRQ_13_1_1A", partName = "Queue_CountTotal_13_1")
        QueueCountTotal queueCountTotal131,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param queueList111
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.qdqlrr_11_1_1a.QueueListReply
     */
    @WebMethod(operationName = "Queue_List", action = "http://webservices.amadeus.com/QDQLRQ_11_1_1A")
    @WebResult(name = "Queue_ListReply", targetNamespace = "http://xml.amadeus.com/QDQLRR_11_1_1A", partName = "Queue_ListReply_11_1")
    public QueueListReply queueList(
        @WebParam(name = "Queue_List", targetNamespace = "http://xml.amadeus.com/QDQLRQ_11_1_1A", partName = "Queue_List_11_1")
        QueueList queueList111,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param queueMoveItem31
     * @return
     *     returns com.amadeus.xml.quqmur_03_1_1a.QueueMoveItemReply
     */
    @WebMethod(operationName = "Queue_MoveItem", action = "http://webservices.amadeus.com/QUQMUQ_03_1_1A")
    @WebResult(name = "Queue_MoveItemReply", targetNamespace = "http://xml.amadeus.com/QUQMUR_03_1_1A", partName = "Queue_MoveItemReply_3_1")
    public QueueMoveItemReply queueMoveItem(
        @WebParam(name = "Queue_MoveItem", targetNamespace = "http://xml.amadeus.com/QUQMUQ_03_1_1A", partName = "Queue_MoveItem_3_1")
        QueueMoveItem queueMoveItem31,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param queuePlacePNR31
     * @return
     *     returns com.amadeus.xml.quqpcr_03_1_1a.QueuePlacePNRReply
     */
    @WebMethod(operationName = "Queue_PlacePNR", action = "http://webservices.amadeus.com/QUQPCQ_03_1_1A")
    @WebResult(name = "Queue_PlacePNRReply", targetNamespace = "http://xml.amadeus.com/QUQPCR_03_1_1A", partName = "Queue_PlacePNRReply_3_1")
    public QueuePlacePNRReply queuePlacePNR(
        @WebParam(name = "Queue_PlacePNR", targetNamespace = "http://xml.amadeus.com/QUQPCQ_03_1_1A", partName = "Queue_PlacePNR_3_1")
        QueuePlacePNR queuePlacePNR31,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param queueRemoveItem31
     * @return
     *     returns com.amadeus.xml.quqmdr_03_1_1a.QueueRemoveItemReply
     */
    @WebMethod(operationName = "Queue_RemoveItem", action = "http://webservices.amadeus.com/QUQMDQ_03_1_1A")
    @WebResult(name = "Queue_RemoveItemReply", targetNamespace = "http://xml.amadeus.com/QUQMDR_03_1_1A", partName = "Queue_RemoveItemReply_3_1")
    public QueueRemoveItemReply queueRemoveItem(
        @WebParam(name = "Queue_RemoveItem", targetNamespace = "http://xml.amadeus.com/QUQMDQ_03_1_1A", partName = "Queue_RemoveItem_3_1")
        QueueRemoveItem queueRemoveItem31,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param securityAuthenticate61
     * @return
     *     returns com.amadeus.xml.vlsslr_06_1_1a.SecurityAuthenticateReply
     */
    @WebMethod(operationName = "Security_Authenticate", action = "http://webservices.amadeus.com/VLSSLQ_06_1_1A")
    @WebResult(name = "Security_AuthenticateReply", targetNamespace = "http://xml.amadeus.com/VLSSLR_06_1_1A", partName = "Security_AuthenticateReply_6_1")
    public SecurityAuthenticateReply securityAuthenticate(
        @WebParam(name = "Security_Authenticate", targetNamespace = "http://xml.amadeus.com/VLSSLQ_06_1_1A", partName = "Security_Authenticate_6_1")
        SecurityAuthenticate securityAuthenticate61,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param link
     * @param securitySignOut41
     * @return
     *     returns com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply
     */
    @WebMethod(operationName = "Security_SignOut", action = "http://webservices.amadeus.com/VLSSOQ_04_1_1A")
    @WebResult(name = "Security_SignOutReply", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", partName = "Security_SignOutReply_4_1")
    public SecuritySignOutReply securitySignOut(
        @WebParam(name = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A", partName = "Security_SignOut_4_1")
        SecuritySignOut securitySignOut41,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param session
     * @param ticketCreateTSTFromPricing41
     * @param link
     * @return
     *     returns com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply
     */
    @WebMethod(operationName = "Ticket_CreateTSTFromPricing", action = "http://webservices.amadeus.com/TAUTCQ_04_1_1A")
    @WebResult(name = "Ticket_CreateTSTFromPricingReply", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", partName = "Ticket_CreateTSTFromPricingReply_4_1")
    public TicketCreateTSTFromPricingReply ticketCreateTSTFromPricing(
        @WebParam(name = "Ticket_CreateTSTFromPricing", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A", partName = "Ticket_CreateTSTFromPricing_4_1")
        TicketCreateTSTFromPricing ticketCreateTSTFromPricing41,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param ticketProcessEDoc152
     * @param security
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.tatres_15_2_1a.TicketProcessEDocReply
     */
    @WebMethod(operationName = "Ticket_ProcessEDoc", action = "http://webservices.amadeus.com/TATREQ_15_2_1A")
    @WebResult(name = "Ticket_ProcessEDocReply", targetNamespace = "http://xml.amadeus.com/TATRES_15_2_1A", partName = "Ticket_ProcessEDocReply_15_2")
    public TicketProcessEDocReply ticketProcessEDoc(
        @WebParam(name = "Ticket_ProcessEDoc", targetNamespace = "http://xml.amadeus.com/TATREQ_15_2_1A", partName = "Ticket_ProcessEDoc_15_2")
        TicketProcessEDoc ticketProcessEDoc152,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param security
     * @param ticketProcessETicket41
     * @param session
     * @param link
     * @return
     *     returns com.amadeus.xml.tktres_04_1_ia.TicketProcessETicketReply
     */
    @WebMethod(operationName = "Ticket_ProcessETicket", action = "http://webservices.amadeus.com/TKTREQ_04_1_IA")
    @WebResult(name = "Ticket_ProcessETicketReply", targetNamespace = "http://xml.amadeus.com/TKTRES_04_1_IA", partName = "Ticket_ProcessETicketReply_4_1")
    public TicketProcessETicketReply ticketProcessETicket(
        @WebParam(name = "Ticket_ProcessETicket", targetNamespace = "http://xml.amadeus.com/TKTREQ_04_1_IA", partName = "Ticket_ProcessETicket_4_1")
        TicketProcessETicket ticketProcessETicket41,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

}
