
package com.amadeus.xml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AmadeusWebServices", targetNamespace = "http://xml.amadeus.com", wsdlLocation = "file:C:\\Users\\grupnar\\git\\TravelFramework-git\\src\\main\\resources\\1ASIWAWBNLS_PDT_20171206_044841\\1ASIWAWBNLS_PDT_20171206_044841.wsdl")
public class AmadeusWebServices
    extends Service
{

    private final static URL AMADEUSWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException AMADEUSWEBSERVICES_EXCEPTION;
    private final static QName AMADEUSWEBSERVICES_QNAME = new QName("http://xml.amadeus.com", "AmadeusWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:C:\\Users\\grupnar\\git\\TravelFramework-git\\src\\main\\resources\\1ASIWAWBNLS_PDT_20171206_044841\\1ASIWAWBNLS_PDT_20171206_044841.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AMADEUSWEBSERVICES_WSDL_LOCATION = url;
        AMADEUSWEBSERVICES_EXCEPTION = e;
    }

    public AmadeusWebServices() {
        super(__getWsdlLocation(), AMADEUSWEBSERVICES_QNAME);
    }

    public AmadeusWebServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), AMADEUSWEBSERVICES_QNAME, features);
    }

    public AmadeusWebServices(URL wsdlLocation) {
        super(wsdlLocation, AMADEUSWEBSERVICES_QNAME);
    }

    public AmadeusWebServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AMADEUSWEBSERVICES_QNAME, features);
    }

    public AmadeusWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AmadeusWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AmadeusWebServicesPT
     */
    @WebEndpoint(name = "AmadeusWebServicesPort")
    public AmadeusWebServicesPT getAmadeusWebServicesPort() {
        return super.getPort(new QName("http://xml.amadeus.com", "AmadeusWebServicesPort"), AmadeusWebServicesPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmadeusWebServicesPT
     */
    @WebEndpoint(name = "AmadeusWebServicesPort")
    public AmadeusWebServicesPT getAmadeusWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.amadeus.com", "AmadeusWebServicesPort"), AmadeusWebServicesPT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AMADEUSWEBSERVICES_EXCEPTION!= null) {
            throw AMADEUSWEBSERVICES_EXCEPTION;
        }
        return AMADEUSWEBSERVICES_WSDL_LOCATION;
    }

}
